/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type ServiceUpdateRequest struct {
	AppId string `json:"appId"`
	Options map[string]map[string]interface{} `json:"options,omitempty"`
	PackageName string `json:"packageName,omitempty"`
	PackageVersion string `json:"packageVersion,omitempty"`
	// If true any stored configuration will be ignored when producing the updated service configuration.
	Replace bool `json:"replace"`
}
