/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type V30Resource struct {
	Assets Assets `json:"assets,omitempty"`
	Cli Cli `json:"cli,omitempty"`
	Images Images `json:"images,omitempty"`
}
