/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type UninstallResponse struct {
	AppId string `json:"appId"`
	PackageName string `json:"packageName"`
	PackageVersion string `json:"packageVersion,omitempty"`
	PostUninstallNotes string `json:"postUninstallNotes,omitempty"`
}
