/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type Licence struct {
	// The name of the license. For example one of [Apache License Version 2.0 | MIT License | BSD License | Proprietary]
	Name string `json:"name"`
	Url string `json:"url"`
}
