/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type UninstallRequest struct {
	AppId string `json:"appId,omitempty"`
	PackageName string `json:"packageName"`
	All bool `json:"all,omitempty"`
}
