/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos
type Algo string

// List of algo
const (
	SHA256 Algo = "sha256"
)