/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type ModelError struct {
	Type string `json:"type"`
	Message string `json:"message"`
	Data map[string]interface{} `json:"data,omitempty"`
}
