/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type Assets struct {
	Container AssetsContainer `json:"container,omitempty"`
	Uris map[string]string `json:"uris,omitempty"`
}
