/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dcos

type PackageDeleteRepoRequest struct {
	Name string `json:"name,omitempty"`
	Uri string `json:"uri,omitempty"`
}
